### PR TITLE
Fixed send and receive functionality for Android 6 and above.

### PR DESCRIPTION
**Pull request by TDFKAOlli**
Have an Android 6 phone now and found a number of issues with the last send/receive implementation and additional coded needed for access rights to external memory:

Rights management forbids file scheme sharing and instead we need to use content schemes. Filters adapted accordingly.

Additionally the application must request for external memory read/write rights, regardless of the manifest settings. Certain functionality (import, export, send, receive) is blocked as long as rights are not given.

### CODE REVIEW

**Comment by TDFKAOlli** [comment]
Hi,
could you drop a new version to play? I need to distribute to other phones and doing with my own build version with debug key I wouldn't prefer.
Thanks!

**Comment by xargsgrep** [comment]
Sorry about that, I'll get the new release out this weekend.

**Comment by xargsgrep** [comment]
@TDFKAOlli I just published to the play store now, you should see it within a few hours. Thanks!

**Comment by TDFKAOlli** [comment]
Great! Just pulled the actual version from play. Thanks a lot!

Am 25.02.2017 um 21:06 schrieb Ahsan Rabbani:

**Pull request merged**
